org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
systemProp.http.socketTimeout=600000
systemProp.http.connectionTimeout=600000
systemProp.https.socketTimeout=600000
systemProp.https.connectionTimeout=600000
android.useAndroidX=true
android.builtInKotlin=false
android.newDsl=false
kotlin.compiler.execution.strategy=in-process
